### ISSUE TITLE
Assignment 1 - Login / SignUp

### ISSUE THREAD

**Issue by uhgenie7** [uhj1993/todoList-With-TanStack-Query#1]
# Assignment 1 - Login / SignUp
- /auth 경로에 로그인 / 회원가입 기능을 개발합니다
  - 로그인, 회원가입을 별도의 경로로 분리해도 무방합니다
  - [x] 최소한 이메일, 비밀번호 input, 제출 button을 갖도록 구성해주세요
- 이메일과 비밀번호의 유효성을 확인합니다
   - [x] 이메일 조건 : 최소 @, . 포함
   - [x] 비밀번호 조건 : 8자 이상 입력
   - [x] 이메일과 비밀번호가 모두 입력되어 있고, 조건을 만족해야 제출 버튼이 활성화 되도록 해주세요
- 로그인 API를 호출하고, 올바른 응답을 받았을 때 루트 경로로 이동시켜주세요
   - [x] 응답으로 받은 토큰은 로컬 스토리지에 저장해주세요
   - [x]  다음 번에 로그인 시 토큰이 존재한다면 루트 경로로 리다이렉트 시켜주세요
   - [x] 어떤 경우든 토큰이 유효하지 않다면 사용자에게 알리고 로그인 페이지로 리다이렉트 시켜주세요

## Todo
- [x] 로그인 화면
  - [x] Input component
  - [x] Button component
- [x] 회원가입 화면
